AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - talentport-aws-login::springboot-sample
Resources:
  SpringbootSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.talent.port.api.TalentCoreLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://spring-boot-register-aws/20f818ce728228151b0341e0af45c0e0
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /api/create
            Method: POST
Outputs:
  SpringbootSampleApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev
    Export:
      Name: SpringbootSampleApi
