AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - talentport-aws-login::springboot-sample
Resources:
  SpringbootSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.talent.port.api.TalentCoreLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/talentport-Register-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /api/create
            Method: POST

Outputs:
  SpringbootSampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev'
    Export:
      Name: SpringbootSampleApi
